import type { Metadata } from "next";
import "./globals.css";
import { Fustat } from "next/font/google";

const fustat = Fustat({ subsets: ['latin'], weight: ['200','300','400','500','600','700','800'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fustat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
